
package org.ssm.dufy.client.wms.cancel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WmsCkdel", targetNamespace = "http://wservice.ckdel/", wsdlLocation = "http://10.6.0.110:8082/taslyedi/services/tianjin/cerp_and_lims/lims/WmsCkdel?wsdl")
public class WmsCkdel
    extends Service
{

    private final static URL WMSCKDEL_WSDL_LOCATION;
    private final static WebServiceException WMSCKDEL_EXCEPTION;
    private final static QName WMSCKDEL_QNAME = new QName("http://wservice.ckdel/", "WmsCkdel");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.0.110:8082/taslyedi/services/tianjin/cerp_and_lims/lims/WmsCkdel?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMSCKDEL_WSDL_LOCATION = url;
        WMSCKDEL_EXCEPTION = e;
    }

    public WmsCkdel() {
        super(__getWsdlLocation(), WMSCKDEL_QNAME);
    }

    public WmsCkdel(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMSCKDEL_QNAME, features);
    }

    public WmsCkdel(URL wsdlLocation) {
        super(wsdlLocation, WMSCKDEL_QNAME);
    }

    public WmsCkdel(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMSCKDEL_QNAME, features);
    }

    public WmsCkdel(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsCkdel(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmsCkdelSoap
     */
    @WebEndpoint(name = "WmsCkdelSoap")
    public WmsCkdelSoap getWmsCkdelSoap() {
        return super.getPort(new QName("http://wservice.ckdel/", "WmsCkdelSoap"), WmsCkdelSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsCkdelSoap
     */
    @WebEndpoint(name = "WmsCkdelSoap")
    public WmsCkdelSoap getWmsCkdelSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.ckdel/", "WmsCkdelSoap"), WmsCkdelSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMSCKDEL_EXCEPTION!= null) {
            throw WMSCKDEL_EXCEPTION;
        }
        return WMSCKDEL_WSDL_LOCATION;
    }

}
