
package org.ssm.dufy.client.orderreturninfo;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrderReturnInfoService", targetNamespace = "http://service.erp.oms.tasly.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOrderReturnInfoService {


    /**
     * 
     * @param orderResultInfo
     */
    @WebMethod(operationName = "OrderResultReturn")
    @Oneway
    @RequestWrapper(localName = "OrderResultReturn", targetNamespace = "http://service.erp.oms.tasly.com/", className = "org.ssm.dufy.client.orderreturninfo.OrderResultReturn")
    public void orderResultReturn(
        @WebParam(name = "OrderResultInfo", targetNamespace = "")
        OrderReturnInfoReqObj orderResultInfo);

}
