//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:35:20 ���� CST 
//


package org.ssm.cxf.struct.insider;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insiderinfo"
})
@XmlRootElement(name = "INSIDERINFO_RESP")
public class INSIDERINFORESP {

    @XmlElement(name = "INSIDERINFO", required = true)
    protected List<INSIDERINFO> insiderinfo;

    public List<INSIDERINFO> getINSIDERINFO() {
        if (insiderinfo == null) {
        	insiderinfo = new ArrayList<INSIDERINFO>();
        }
        return this.insiderinfo;
    }

}
