//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:29:22 ���� CST 
//


package org.ssm.cxf.struct.insider;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insiderid",
    "mobile",
    "ym"
})
@XmlRootElement(name = "INSIDERINFO_REQ")
public class INSIDERINFOREQ {

    @XmlElement(name = "INSIDERID", required = true)
    protected String insiderid;
    @XmlElement(name = "MOBILE", required = true)
    protected String mobile;
    @XmlElement(name = "YM", required = true)
    protected String ym;

    /**
     * Gets the value of the insiderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSIDERID() {
        return insiderid;
    }

    /**
     * Sets the value of the insiderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSIDERID(String value) {
        this.insiderid = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOBILE() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOBILE(String value) {
        this.mobile = value;
    }

   

    /**
     * Gets the value of the ym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYM() {
        return ym;
    }

    /**
     * Sets the value of the ym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYM(String value) {
        this.ym = value;
    }

}
