//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:35:20 ���� CST 
//


package org.ssm.cxf.struct.insider;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insiderid",
    "insidername",
    "sex",
    "birthdate",
    "integral",
    "entrycompanyid",
    "mobile"
})
@XmlRootElement(name = "INSIDERINFO")
public class INSIDERINFO {

    @XmlElement(required = true)
    protected String insiderid;
    
    @XmlElement(required = true)
    protected String insidername;
    
    @XmlElement(required = true)
    protected String sex;
    
    @XmlElement(required = true)
    protected String birthdate;
    
    @XmlElement(required = true)
    protected String integral;
    
    @XmlElement(required = true)
    protected String mobile;
    
    @XmlElement(required = true)
    protected String entrycompanyid;

    
	public String getInsiderid() {
		return insiderid;
	}

	public void setInsiderid(String insiderid) {
		this.insiderid = insiderid;
	}

	public String getInsidername() {
		return insidername;
	}

	public void setInsidername(String insidername) {
		this.insidername = insidername;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	public String getIntegral() {
		return integral;
	}

	public void setIntegral(String integral) {
		this.integral = integral;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEntrycompanyid() {
		return entrycompanyid;
	}

	public void setEntrycompanyid(String entrycompanyid) {
		this.entrycompanyid = entrycompanyid;
	}
    
    

}
