//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:29:22 ���� CST 
//


package org.ssm.cxf.struct.pointpolicy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "goodsid",
    "entrycompanyid",
    "sysmodifydate",
    "ym"
})
@XmlRootElement(name = "POINTPOLICYINFO_REQ")
public class POINTPOLICYINFOREQ {

    @XmlElement(name = "GOODSID", required = true)
    protected String goodsid;
    @XmlElement(name = "ENTRYCOMPANYID", required = true)
    protected String entrycompanyid;
    @XmlElement(name = "SYS_MODIFYDATE", required = true)
    protected String sysmodifydate;
    @XmlElement(name = "YM", required = true)
    protected String ym;

    /**
     * Gets the value of the goodsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGOODSID() {
        return goodsid;
    }

    /**
     * Sets the value of the goodsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGOODSID(String value) {
        this.goodsid = value;
    }

    /**
     * Gets the value of the entrycompanyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTRYCOMPANYID() {
        return entrycompanyid;
    }

    /**
     * Sets the value of the entrycompanyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTRYCOMPANYID(String value) {
        this.entrycompanyid = value;
    }
    
    public String getSYSMODIFYDATE() {
        return sysmodifydate;
    }

    public void setSYSMODIFYDATE(String value) {
        this.sysmodifydate = value;
    }

   

    /**
     * Gets the value of the ym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYM() {
        return ym;
    }

    /**
     * Sets the value of the ym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYM(String value) {
        this.ym = value;
    }

}
