//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:35:20 ���� CST 
//


package org.ssm.cxf.struct.pointpolicy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pointpolicyinfo"
})
@XmlRootElement(name = "POINTPOLICYINFO_RESP")
public class POINTPOLICYINFORESP {

    @XmlElement(name = "POINTPOLICYINFO", required = true)
    protected List<POINTPOLICYINFO> pointpolicyinfo;

    public List<POINTPOLICYINFO> getINSIDERINFO() {
        if (pointpolicyinfo == null) {
        	pointpolicyinfo = new ArrayList<POINTPOLICYINFO>();
        }
        return this.pointpolicyinfo;
    }

}
