//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 04:35:20 ���� CST 
//


package org.ssm.cxf.struct.goodsinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}goodsid"/>
 *         &lt;element ref="{}goodsname"/>
 *         &lt;element ref="{}goodsunit"/>
 *         &lt;element ref="{}goodstype"/>
 *         &lt;element ref="{}currencyname"/>
 *         &lt;element ref="{}factoryname"/>
 *         &lt;element ref="{}entryid"/>
 *         &lt;element ref="{}barcode"/>
 *         &lt;element ref="{}sys_modifydate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "goodsid",
    "goodsname",
    "goodsunit",
    "goodstype",
    "currencyname",
    "factoryname",
    "entryid",
    "barcode",
    "sysModifydate",
    "entrycompanyid"
})
@XmlRootElement(name = "GOODSINFO")
public class GOODSINFO {

    @XmlElement(required = true)
    protected String goodsid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String goodsname;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String goodsunit;
    @XmlElement(required = true)
    protected String goodstype;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currencyname;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String factoryname;
    @XmlElement(required = true)
    protected String entryid;
    @XmlElement(required = true)
    protected String barcode;
    @XmlElement(name = "sys_modifydate", required = true)
    protected String sysModifydate;
    
    @XmlElement(required = true)
    protected String entrycompanyid;

    /**
     * Gets the value of the goodsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * Sets the value of the goodsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsid(String value) {
        this.goodsid = value;
    }

    /**
     * Gets the value of the goodsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * Sets the value of the goodsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsname(String value) {
        this.goodsname = value;
    }

    /**
     * Gets the value of the goodsunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsunit() {
        return goodsunit;
    }

    /**
     * Sets the value of the goodsunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsunit(String value) {
        this.goodsunit = value;
    }

    /**
     * Gets the value of the goodstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodstype() {
        return goodstype;
    }

    /**
     * Sets the value of the goodstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodstype(String value) {
        this.goodstype = value;
    }

    /**
     * Gets the value of the currencyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyname() {
        return currencyname;
    }

    /**
     * Sets the value of the currencyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyname(String value) {
        this.currencyname = value;
    }

    /**
     * Gets the value of the factoryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryname() {
        return factoryname;
    }

    /**
     * Sets the value of the factoryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryname(String value) {
        this.factoryname = value;
    }

    /**
     * Gets the value of the entryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryid() {
        return entryid;
    }

    /**
     * Sets the value of the entryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryid(String value) {
        this.entryid = value;
    }

    /**
     * Gets the value of the barcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the sysModifydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysModifydate() {
        return sysModifydate;
    }

    /**
     * Sets the value of the sysModifydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysModifydate(String value) {
        this.sysModifydate = value;
    }

	public String getEntrycompanyid() {
		return entrycompanyid;
	}

	public void setEntrycompanyid(String entrycompanyid) {
		this.entrycompanyid = entrycompanyid;
	}
    
    

}
