
package org.ssm.dufy.client.wms.edit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WmsCkkpdMod", targetNamespace = "http://wservice.ckkpdmod/", wsdlLocation = "http://10.6.0.110:8082/taslyedi/services/tianjin/cerp_and_lims/lims/WmsCkkpdMod?wsdl")
public class WmsCkkpdMod
    extends Service
{

    private final static URL WMSCKKPDMOD_WSDL_LOCATION;
    private final static WebServiceException WMSCKKPDMOD_EXCEPTION;
    private final static QName WMSCKKPDMOD_QNAME = new QName("http://wservice.ckkpdmod/", "WmsCkkpdMod");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.0.110:8082/taslyedi/services/tianjin/cerp_and_lims/lims/WmsCkkpdMod?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMSCKKPDMOD_WSDL_LOCATION = url;
        WMSCKKPDMOD_EXCEPTION = e;
    }

    public WmsCkkpdMod() {
        super(__getWsdlLocation(), WMSCKKPDMOD_QNAME);
    }

    public WmsCkkpdMod(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMSCKKPDMOD_QNAME, features);
    }

    public WmsCkkpdMod(URL wsdlLocation) {
        super(wsdlLocation, WMSCKKPDMOD_QNAME);
    }

    public WmsCkkpdMod(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMSCKKPDMOD_QNAME, features);
    }

    public WmsCkkpdMod(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsCkkpdMod(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmsCkkpdModSoap
     */
    @WebEndpoint(name = "WmsCkkpdModSoap")
    public WmsCkkpdModSoap getWmsCkkpdModSoap() {
        return super.getPort(new QName("http://wservice.ckkpdmod/", "WmsCkkpdModSoap"), WmsCkkpdModSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsCkkpdModSoap
     */
    @WebEndpoint(name = "WmsCkkpdModSoap")
    public WmsCkkpdModSoap getWmsCkkpdModSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.ckkpdmod/", "WmsCkkpdModSoap"), WmsCkkpdModSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMSCKKPDMOD_EXCEPTION!= null) {
            throw WMSCKKPDMOD_EXCEPTION;
        }
        return WMSCKKPDMOD_WSDL_LOCATION;
    }

}
