
package org.ssm.dufy.client.wms.edit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WmsCkkpdModSoap", targetNamespace = "http://wservice.ckkpdmod/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmsCkkpdModSoap {


    /**
     * 
     * @param iREQUEST
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReceiveCkkpdMod", action = "http://wservice.ckkpdmod/ReceiveCkkpdMod")
    @WebResult(name = "ReceiveCkkpdModResult", targetNamespace = "http://wservice.ckkpdmod/")
    @RequestWrapper(localName = "ReceiveCkkpdMod", targetNamespace = "http://wservice.ckkpdmod/", className = "org.ssm.dufy.client.wms.edit.ReceiveCkkpdMod")
    @ResponseWrapper(localName = "ReceiveCkkpdModResponse", targetNamespace = "http://wservice.ckkpdmod/", className = "org.ssm.dufy.client.wms.edit.ReceiveCkkpdModResponse")
    public String receiveCkkpdMod(
        @WebParam(name = "I_REQUEST", targetNamespace = "http://wservice.ckkpdmod/")
        INFDATA iREQUEST);

}
